import parkingLotImage from "../../../assets/images/parking-hero.jpg";
export default {
  hero: {
    position: "relative",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundImage: `url(${parkingLotImage})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    overflow: "hidden",
    px: 0,
  },
  overlay: {
    position: "absolute",
    inset: 0,
    backdropFilter: "blur(6px)",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    zIndex: 1,
    pointerEvents: "none",
  },
  blurBox: {
    position: "relative",
    zIndex: 2,
    padding: "2rem",
    borderRadius: "12px",
    maxWidth: "800px",
    width: "100%",
    mx: "auto",
    color: "#fff",
    pointerEvents: "auto",
  },
  heading: {
    fontWeight: "bold",
    fontSize: { xs: "1.75rem", md: "2.5rem" },
    mb: 3,
    textShadow: "0 1px 4px rgba(0,0,0,0.4)",
  },
  searchContainer: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: "8px",
    padding: "6px 12px",
    gap: 1,
    width: "100%",
    maxWidth: "600px",
    mx: "auto",
  },
  searchIcon: {
    color: "#666",
  },
  searchInput: {
    flex: 1,
    color: "#333",
  },
  button: {
    whiteSpace: "nowrap",
  },
};
